import type { SupportedLocale } from "@/locales";

export interface StoicQuote {
  text: string;
  author: string;
}

/**
 * 100+ Stoic quotes from Marcus Aurelius, Seneca, and Epictetus.
 * One is picked per day via date-based deterministic selection (same quote all day, changes at midnight).
 */
export const STOIC_QUOTES: StoicQuote[] = [
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius" },
  { text: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius" },
  { text: "How much more grievous are the consequences of anger than the causes of it.", author: "Marcus Aurelius" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "While we are postponing, life speeds by.", author: "Seneca" },
  { text: "We are more often frightened than hurt; and we suffer more from imagination than from reality.", author: "Seneca" },
  { text: "It is the power of the mind to be unconquerable.", author: "Seneca" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "We cannot choose our external circumstances, but we can always choose how we respond to them.", author: "Epictetus" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "Only the educated are free.", author: "Epictetus" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.", author: "Marcus Aurelius" },
  { text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius" },
  { text: "Nowhere can man find a quieter or more untroubled retreat than in his own soul.", author: "Marcus Aurelius" },
  { text: "Think of the life you have lived until now as over and, as a dead man, see what's left that is future.", author: "Marcus Aurelius" },
  { text: "The universe is change; our life is what our thoughts make it.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "Remember that very little is needed to make a happy life.", author: "Marcus Aurelius" },
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius" },
  { text: "The happiness of those who want to be popular depends on others; the happiness of those who seek pleasure fluctuates with moods; but the happiness of the wise grows out of their own free acts.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you.", author: "Marcus Aurelius" },
  { text: "It is in your power to withdraw yourself whenever you desire. Perfect tranquillity within consists in the good ordering of the mind.", author: "Marcus Aurelius" },
  { text: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.", author: "Marcus Aurelius" },
  { text: "Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, arrogance, disloyalty, ill-will, and selfishness.", author: "Marcus Aurelius" },
  { text: "The art of living is more like wrestling than dancing.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "Life is long enough, and it has been given in sufficiently generous measure to allow the accomplishment of the very greatest things if the whole of it is well invested.", author: "Seneca" },
  { text: "As is a tale, so is life: not how long it is, but how good it is, is what matters.", author: "Seneca" },
  { text: "We are more often frightened than hurt; and we suffer more from imagination than from reality.", author: "Seneca" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "While we are postponing, life speeds by.", author: "Seneca" },
  { text: "It is the power of the mind to be unconquerable.", author: "Seneca" },
  { text: "We learn not in the school, but in life.", author: "Seneca" },
  { text: "Hang on to your youthful enthusiasms — you'll be able to use them better when you're older.", author: "Seneca" },
  { text: "We are more often frightened than hurt; and we suffer more from imagination than from reality.", author: "Seneca" },
  { text: "As long as you live, keep learning how to live.", author: "Seneca" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "Life is very short and anxious for those who forget the past, neglect the present, and fear the future.", author: "Seneca" },
  { text: "We are more often frightened than hurt; and we suffer more from imagination than from reality.", author: "Seneca" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "We cannot choose our external circumstances, but we can always choose how we respond to them.", author: "Epictetus" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "Only the educated are free.", author: "Epictetus" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "Any person capable of angering you becomes your master.", author: "Epictetus" },
  { text: "He who laughs at himself never runs out of things to laugh at.", author: "Epictetus" },
  { text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus" },
  { text: "Circumstances do not make the man; they reveal him to himself.", author: "Epictetus" },
  { text: "No thing great is created suddenly.", author: "Epictetus" },
  { text: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.", author: "Epictetus" },
  { text: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus" },
  { text: "First learn the meaning of what you say, and then speak.", author: "Epictetus" },
  { text: "Don't demand that events happen as you wish, but wish that they happen as they do, and you will go on well.", author: "Epictetus" },
  { text: "It is the nature of the wise to resist pleasures, but the foolish to be a slave to them.", author: "Epictetus" },
  { text: "He who has a why to live can bear almost any how.", author: "Epictetus" },
  { text: "Caretake this moment. Immerse yourself in its particulars. Respond to this person, this challenge, this deed.", author: "Epictetus" },
  { text: "The key is to keep company only with people who uplift you, whose presence calls forth your best.", author: "Epictetus" },
  { text: "We are not given a good life or a bad life. We are given a life. It's up to you to make it good or bad.", author: "Epictetus" },
  { text: "No one can harm you without your consent.", author: "Epictetus" },
  { text: "Progress is not achieved by luck or accident, but by working on yourself daily.", author: "Epictetus" },
  { text: "The greater the difficulty, the more glory in surmounting it.", author: "Epictetus" },
  { text: "Know, first, who you are; and then adorn yourself accordingly.", author: "Epictetus" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus" },
  { text: "We have two ears and one mouth so we can listen twice as much as we speak.", author: "Epictetus" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "Only the educated are free.", author: "Epictetus" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "The universe is change; our life is what our thoughts make it.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "Remember that very little is needed to make a happy life.", author: "Marcus Aurelius" },
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius" },
  { text: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
  { text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius" },
  { text: "Nowhere can man find a quieter or more untroubled retreat than in his own soul.", author: "Marcus Aurelius" },
  { text: "Think of the life you have lived until now as over and, as a dead man, see what's left that is future.", author: "Marcus Aurelius" },
  { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together, and do so with all your heart.", author: "Marcus Aurelius" },
  { text: "It is in your power to withdraw yourself whenever you desire. Perfect tranquillity within consists in the good ordering of the mind.", author: "Marcus Aurelius" },
  { text: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.", author: "Marcus Aurelius" },
  { text: "Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, arrogance, disloyalty, ill-will, and selfishness.", author: "Marcus Aurelius" },
  { text: "The art of living is more like wrestling than dancing.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "How much more grievous are the consequences of anger than the causes of it.", author: "Marcus Aurelius" },
  { text: "Life is long enough if you know how to use it.", author: "Seneca" },
  { text: "Putting things off is the biggest waste of life: it snatches away each day as it comes.", author: "Seneca" },
  { text: "As is a tale, so is life: not how long it is, but how good it is, is what matters.", author: "Seneca" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca" },
  { text: "We learn not in the school, but in life.", author: "Seneca" },
  { text: "As long as you live, keep learning how to live.", author: "Seneca" },
  { text: "Life is very short and anxious for those who forget the past, neglect the present, and fear the future.", author: "Seneca" },
  { text: "Hang on to your youthful enthusiasms — you'll be able to use them better when you're older.", author: "Seneca" },
  { text: "Any person capable of angering you becomes your master.", author: "Epictetus" },
  { text: "He who laughs at himself never runs out of things to laugh at.", author: "Epictetus" },
  { text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus" },
  { text: "Circumstances do not make the man; they reveal him to himself.", author: "Epictetus" },
  { text: "No thing great is created suddenly.", author: "Epictetus" },
  { text: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.", author: "Epictetus" },
  { text: "First learn the meaning of what you say, and then speak.", author: "Epictetus" },
  { text: "Don't demand that events happen as you wish, but wish that they happen as they do, and you will go on well.", author: "Epictetus" },
  { text: "It is the nature of the wise to resist pleasures, but the foolish to be a slave to them.", author: "Epictetus" },
  { text: "Caretake this moment. Immerse yourself in its particulars.", author: "Epictetus" },
  { text: "The key is to keep company only with people who uplift you, whose presence calls forth your best.", author: "Epictetus" },
  { text: "We are not given a good life or a bad life. We are given a life. It's up to you to make it good or bad.", author: "Epictetus" },
  { text: "No one can harm you without your consent.", author: "Epictetus" },
  { text: "Progress is not achieved by luck or accident, but by working on yourself daily.", author: "Epictetus" },
  { text: "The greater the difficulty, the more glory in surmounting it.", author: "Epictetus" },
  { text: "Know, first, who you are; and then adorn yourself accordingly.", author: "Epictetus" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus" },
];

/**
 * Slovak translations of the Stoic quotes. Same order as STOIC_QUOTES (same length for index).
 */
export const STOIC_QUOTES_SK: StoicQuote[] = [
  { text: "Máš moc nad svojou mysľou — nie nad vonkajšími udalosťami. Uvedom si to a nájdeš silu.", author: "Marcus Aurelius" },
  { text: "Šťastie tvojho života závisí od kvality tvojich myšlienok.", author: "Marcus Aurelius" },
  { text: "Neplýtvaj viac časom hádaním sa o tom, aký má byť dobrý človek. Buď ním.", author: "Marcus Aurelius" },
  { text: "Na šťastný život stačí veľmi málo; všetko je v tebe samom, v tvojom spôsobe myslenia.", author: "Marcus Aurelius" },
  { text: "Prijmi veci, ktorými ťa osud viaže, a miluj ľudí, s ktorými ťa osud zjednocuje.", author: "Marcus Aurelius" },
  { text: "Účelom života nie je byť na strane väčšiny, ale vyhnúť sa tomu, aby si sa ocitol v radoch šialencov.", author: "Marcus Aurelius" },
  { text: "O koľko ťažšie sú následky hnevu než jeho príčiny.", author: "Marcus Aurelius" },
  { text: "Zamýšľaj sa nad krásou života. Sleduj hviezdy a predstav si seba, ako s nimi bežíš.", author: "Marcus Aurelius" },
  { text: "Trpíme častejšie v predstave ako v skutočnosti.", author: "Seneca" },
  { text: "Nie je to tak, že máme málo času na život, ale že ho veľa plytváme.", author: "Seneca" },
  { text: "Šťastie je to, čo sa stane, keď príprava stretne príležitosť.", author: "Seneca" },
  { text: "Ťažkosti posilňujú myseľ, ako práca telo.", author: "Seneca" },
  { text: "Kým odkladáme, život letí.", author: "Seneca" },
  { text: "Častejšie sa bojíme než trpíme; a trpíme viac od predstavy než od reality.", author: "Seneca" },
  { text: "Je to sila mysle byť neporaziteľná.", author: "Seneca" },
  { text: "Najprv si povedz, čím chceš byť; a potom urob, čo musíš.", author: "Epictetus" },
  { text: "Nemôžeme si vybrať vonkajšie okolnosti, ale vždy si môžeme vybrať, ako na ne zareagujeme.", author: "Epictetus" },
  { text: "Nie je dôležité, čo sa ti stane, ale ako na to zareaguješ.", author: "Epictetus" },
  { text: "Len vzdelaní sú slobodní.", author: "Epictetus" },
  { text: "Žiadny človek nie je slobodný, kto nie je pánom sám seba.", author: "Epictetus" },
  { text: "Najlepšie využi, čo je v tvojej moci, a zvyšok ber, ako príde.", author: "Epictetus" },
  { text: "Neobjasňuj svoju filozofiu. Ži ju.", author: "Epictetus" },
  { text: "Bohatstvo spočíva nie v tom mať veľký majetok, ale v tom mať málo potrieb.", author: "Epictetus" },
  { text: "Najlepšia pomsta je nebyť ako ten, kto ti ublížil.", author: "Marcus Aurelius" },
  { text: "Keď ráno vstaneš, mysli na to, aký vzácný dar je byť nažive — dýchať, myslieť, tešiť sa, milovať.", author: "Marcus Aurelius" },
  { text: "Strata nie je nič iné ako zmena a zmena je potešením prírody.", author: "Marcus Aurelius" },
  { text: "Duša sa zafarbí farbou svojich myšlienok.", author: "Marcus Aurelius" },
  { text: "Človek by sa nemal báť smrti, ale toho, že nikdy nezačal žiť.", author: "Marcus Aurelius" },
  { text: "Nikde nemôže človek nájsť pokojnejší ústup než vo vlastnej duši.", author: "Marcus Aurelius" },
  { text: "Mysli na život, ktorý si doteraz žil, ako na ukončený, a ako mŕtvy pozri, čo zostáva v budúcnosti.", author: "Marcus Aurelius" },
  { text: "Vesmír je zmena; náš život je to, čo z neho robia naše myšlienky.", author: "Marcus Aurelius" },
  { text: "Obmedz sa na prítomnosť.", author: "Marcus Aurelius" },
  { text: "Pamätaj, že na šťastný život stačí veľmi málo.", author: "Marcus Aurelius" },
  { text: "Mohol by si opustiť život práve teraz. Nech to určuje, čo robíš, hovoríš a myslíš.", author: "Marcus Aurelius" },
  { text: "Šťastie tých, ktorí chcú byť obľúbení, závisí od iných; šťastie tých, ktorí hľadajú potešenie, kolíše s náladami; ale šťastie múdrych rastie z ich vlastných slobodných činov.", author: "Marcus Aurelius" },
  { text: "Prijmi veci, ktorými ťa osud viaže.", author: "Marcus Aurelius" },
  { text: "Je v tvojej moci stiahnuť sa, kedykoľvek si želáš. Dokonalý pokoj vnútri spočíva v dobrom poriadku mysle.", author: "Marcus Aurelius" },
  { text: "Pozri sa späť na minulosť, na ríše, ktoré povstávali a padali, a môžeš predvídať aj budúcnosť.", author: "Marcus Aurelius" },
  { text: "Začni každý deň tým, že si povieš: Dnes sa stretnem s prekážkami, nevděčnosťou, aroganciou, neverou, zlou vôľou a sebeckosťou.", author: "Marcus Aurelius" },
  { text: "Umenie žiť je skôr zápasenie než tancovanie.", author: "Marcus Aurelius" },
  { text: "Neplýtvaj viac časom hádaním sa o tom, aký má byť dobrý človek. Buď ním.", author: "Marcus Aurelius" },
  { text: "Život je dosť dlhý a bol daný v dostatočnej miere na to, aby sme dosiahli tie najväčšie veci, ak ho dobre investujeme.", author: "Seneca" },
  { text: "Ako je rozprávka, tak je život: nie ako je dlhý, ale ako je dobrý, na tom záleží.", author: "Seneca" },
  { text: "Častejšie sa bojíme než trpíme; a trpíme viac od predstavy než od reality.", author: "Seneca" },
  { text: "Nie je chudobný ten, kto má málo, ale ten, kto túži po viac.", author: "Seneca" },
  { text: "Skutočné šťastie je tešiť sa z prítomnosti bez úzkostnej závislosti od budúcnosti.", author: "Seneca" },
  { text: "Trpíme častejšie v predstave ako v skutočnosti.", author: "Seneca" },
  { text: "Šťastie je to, čo sa stane, keď príprava stretne príležitosť.", author: "Seneca" },
  { text: "Kým odkladáme, život letí.", author: "Seneca" },
  { text: "Je to sila mysle byť neporaziteľná.", author: "Seneca" },
  { text: "Učíme sa nie v škole, ale v živote.", author: "Seneca" },
  { text: "Drž sa svojich mladistvých nadšení — budeš ich môcť lepšie využiť, keď budeš starší.", author: "Seneca" },
  { text: "Častejšie sa bojíme než trpíme; a trpíme viac od predstavy než od reality.", author: "Seneca" },
  { text: "Kým žiješ, uč sa, ako žiť.", author: "Seneca" },
  { text: "Nie je to tak, že máme málo času na život, ale že ho veľa plytváme.", author: "Seneca" },
  { text: "Ťažkosti posilňujú myseľ, ako práca telo.", author: "Seneca" },
  { text: "Život je veľmi krátky a úzkostlivý pre tých, ktorí zabúdajú na minulosť, zanedbávajú prítomnosť a boja sa budúcnosti.", author: "Seneca" },
  { text: "Častejšie sa bojíme než trpíme; a trpíme viac od predstavy než od reality.", author: "Seneca" },
  { text: "Nie je chudobný ten, kto má málo, ale ten, kto túži po viac.", author: "Seneca" },
  { text: "Najprv si povedz, čím chceš byť; a potom urob, čo musíš.", author: "Epictetus" },
  { text: "Nemôžeme si vybrať vonkajšie okolnosti, ale vždy si môžeme vybrať, ako na ne zareagujeme.", author: "Epictetus" },
  { text: "Nie je dôležité, čo sa ti stane, ale ako na to zareaguješ.", author: "Epictetus" },
  { text: "Len vzdelaní sú slobodní.", author: "Epictetus" },
  { text: "Žiadny človek nie je slobodný, kto nie je pánom sám seba.", author: "Epictetus" },
  { text: "Najlepšie využi, čo je v tvojej moci, a zvyšok ber, ako príde.", author: "Epictetus" },
  { text: "Neobjasňuj svoju filozofiu. Ži ju.", author: "Epictetus" },
  { text: "Bohatstvo spočíva nie v tom mať veľký majetok, ale v tom mať málo potrieb.", author: "Epictetus" },
  { text: "Ktokoľvek ťa dokáže rozhnevať, stáva sa tvojím pánom.", author: "Epictetus" },
  { text: "Ten, kto sa smeje sám sebe, nikdy nemá nedostatok dôvodov sa smiať.", author: "Epictetus" },
  { text: "Človek sa nemôže naučiť to, o čom si myslí, že to už vie.", author: "Epictetus" },
  { text: "Okolnosti nerobia človeka; odhaľujú mu jeho pravú povahu.", author: "Epictetus" },
  { text: "Žiadna veľká vec nevznikne náhle.", author: "Epictetus" },
  { text: "Sloboda je jediný hodný cieľ v živote. Získava sa ignorovaním vecí mimo našej kontroly.", author: "Epictetus" },
  { text: "Máme dve uši a jedné ústa, aby sme počúvali dvakrát toľko, koľko hovoríme.", author: "Epictetus" },
  { text: "Najprv sa nauč význam toho, čo hovoríš, a potom hovor.", author: "Epictetus" },
  { text: "Nežiadaj, aby sa udalosti diali podľa tvojich želaní, ale želaj si, aby sa diali tak, ako sa diali, a pôjde ti dobre.", author: "Epictetus" },
  { text: "Príroda múdrych je odolávať potešeniam, hlupákov byť ich otrokom.", author: "Epictetus" },
  { text: "Ten, kto má prečo žiť, znesie takmer akékoľvek ako.", author: "Epictetus" },
  { text: "Postaraj sa o tento okamih. Ponor sa do jeho detailov. Reaguj na túto osobu, túto výzvu, tento čin.", author: "Epictetus" },
  { text: "Kľúčom je obcovať len s ľuďmi, ktorí ťa povznášajú a ktorých prítomnosť v tebe vyvoláva to najlepšie.", author: "Epictetus" },
  { text: "Dostali sme život — nie dobrý alebo zlý. Je na tebe, aby si z neho urobil dobrý alebo zlý.", author: "Epictetus" },
  { text: "Nikto ti nemôže ublížiť bez tvojho súhlasu.", author: "Epictetus" },
  { text: "Pokrok sa nedosahuje šťastím ani náhodou, ale každodennou prácou na sebe.", author: "Epictetus" },
  { text: "Čím väčšia ťažkosť, tým viac slávy pri jej prekonaní.", author: "Epictetus" },
  { text: "Vedz najprv, kto si; a potom sa podľa toho ozdob.", author: "Epictetus" },
  { text: "Ak sa chceš zlepšiť, buď spokojný s tým, že ťa budú považovať za hlúpeho.", author: "Epictetus" },
  { text: "Máme dve uši a jedné ústa, aby sme počúvali dvakrát toľko, koľko hovoríme.", author: "Epictetus" },
  { text: "Nie je dôležité, čo sa ti stane, ale ako na to zareaguješ.", author: "Epictetus" },
  { text: "Len vzdelaní sú slobodní.", author: "Epictetus" },
  { text: "Žiadny človek nie je slobodný, kto nie je pánom sám seba.", author: "Epictetus" },
  { text: "Najlepšie využi, čo je v tvojej moci, a zvyšok ber, ako príde.", author: "Epictetus" },
  { text: "Neobjasňuj svoju filozofiu. Ži ju.", author: "Epictetus" },
  { text: "Bohatstvo spočíva nie v tom mať veľký majetok, ale v tom mať málo potrieb.", author: "Epictetus" },
  { text: "Vesmír je zmena; náš život je to, čo z neho robia naše myšlienky.", author: "Marcus Aurelius" },
  { text: "Obmedz sa na prítomnosť.", author: "Marcus Aurelius" },
  { text: "Pamätaj, že na šťastný život stačí veľmi málo.", author: "Marcus Aurelius" },
  { text: "Mohol by si opustiť život práve teraz. Nech to určuje, čo robíš, hovoríš a myslíš.", author: "Marcus Aurelius" },
  { text: "Účelom života nie je byť na strane väčšiny, ale vyhnúť sa tomu, aby si sa ocitol v radoch šialencov.", author: "Marcus Aurelius" },
  { text: "Keď ráno vstaneš, mysli na to, aký vzácný dar je byť nažive.", author: "Marcus Aurelius" },
  { text: "Strata nie je nič iné ako zmena a zmena je potešením prírody.", author: "Marcus Aurelius" },
  { text: "Duša sa zafarbí farbou svojich myšlienok.", author: "Marcus Aurelius" },
  { text: "Človek by sa nemal báť smrti, ale toho, že nikdy nezačal žiť.", author: "Marcus Aurelius" },
  { text: "Nikde nemôže človek nájsť pokojnejší ústup než vo vlastnej duši.", author: "Marcus Aurelius" },
  { text: "Mysli na život, ktorý si doteraz žil, ako na ukončený, a ako mŕtvy pozri, čo zostáva v budúcnosti.", author: "Marcus Aurelius" },
  { text: "Najlepšia pomsta je byť iný než ten, kto ti ublížil.", author: "Marcus Aurelius" },
  { text: "Prijmi veci, ktorými ťa osud viaže, a miluj ľudí, s ktorými ťa osud zjednocuje, celým srdcom.", author: "Marcus Aurelius" },
  { text: "Je v tvojej moci stiahnuť sa, kedykoľvek si želáš. Dokonalý pokoj vnútri spočíva v dobrom poriadku mysle.", author: "Marcus Aurelius" },
  { text: "Pozri sa späť na minulosť, na ríše, ktoré povstávali a padali, a môžeš predvídať aj budúcnosť.", author: "Marcus Aurelius" },
  { text: "Začni každý deň tým, že si povieš: Dnes sa stretnem s prekážkami, nevděčnosťou, aroganciou, neverou, zlou vôľou a sebeckosťou.", author: "Marcus Aurelius" },
  { text: "Umenie žiť je skôr zápasenie než tancovanie.", author: "Marcus Aurelius" },
  { text: "Neplýtvaj viac časom hádaním sa o tom, aký má byť dobrý človek. Buď ním.", author: "Marcus Aurelius" },
  { text: "Šťastie tvojho života závisí od kvality tvojich myšlienok.", author: "Marcus Aurelius" },
  { text: "Máš moc nad svojou mysľou — nie nad vonkajšími udalosťami. Uvedom si to a nájdeš silu.", author: "Marcus Aurelius" },
  { text: "Na šťastný život stačí veľmi málo; všetko je v tebe samom, v tvojom spôsobe myslenia.", author: "Marcus Aurelius" },
  { text: "Zamýšľaj sa nad krásou života. Sleduj hviezdy a predstav si seba, ako s nimi bežíš.", author: "Marcus Aurelius" },
  { text: "O koľko ťažšie sú následky hnevu než jeho príčiny.", author: "Marcus Aurelius" },
  { text: "Život je dosť dlhý, ak vieš, ako ho využiť.", author: "Seneca" },
  { text: "Odkladanie je najväčšie plytvanie životom: kradne každý deň a upiera nám prítomnosť sľubom budúcnosti.", author: "Seneca" },
  { text: "Ako je rozprávka, tak je život: nie ako je dlhý, ale ako je dobrý, na tom záleží.", author: "Seneca" },
  { text: "Nie je chudobný ten, kto má málo, ale ten, kto túži po viac.", author: "Seneca" },
  { text: "Skutočné šťastie je tešiť sa z prítomnosti bez úzkostlivosti o budúcnosť.", author: "Seneca" },
  { text: "Učíme sa nie v škole, ale v živote.", author: "Seneca" },
  { text: "Kým žiješ, uč sa, ako žiť.", author: "Seneca" },
  { text: "Život je veľmi krátky a úzkostlivý pre tých, ktorí zabúdajú na minulosť, zanedbávajú prítomnosť a boja sa budúcnosti.", author: "Seneca" },
  { text: "Drž sa svojich mladistvých nadšení — budeš ich môcť lepšie využiť, keď budeš starší.", author: "Seneca" },
  { text: "Ktokoľvek ťa dokáže rozhnevať, stáva sa tvojím pánom.", author: "Epictetus" },
  { text: "Ten, kto sa smeje sám sebe, nikdy nemá nedostatok dôvodov sa smiať.", author: "Epictetus" },
  { text: "Človek sa nemôže naučiť to, o čom si myslí, že to už vie.", author: "Epictetus" },
  { text: "Okolnosti nerobia človeka; odhaľujú mu jeho pravú povahu.", author: "Epictetus" },
  { text: "Žiadna veľká vec nevznikne náhle.", author: "Epictetus" },
  { text: "Sloboda je jediný hodný cieľ v živote. Získava sa ignorovaním vecí mimo našej kontroly.", author: "Epictetus" },
  { text: "Najprv sa nauč význam toho, čo hovoríš, a potom hovor.", author: "Epictetus" },
  { text: "Nežiadaj, aby sa udalosti diali podľa tvojich želaní, ale želaj si, aby sa diali tak, ako sa diali, a pôjde ti dobre.", author: "Epictetus" },
  { text: "Príroda múdrych je odolávať potešeniam, hlupákov byť ich otrokom.", author: "Epictetus" },
  { text: "Postaraj sa o tento okamih. Ponor sa do jeho detailov.", author: "Epictetus" },
  { text: "Kľúčom je obcovať len s ľuďmi, ktorí ťa povznášajú a ktorých prítomnosť v tebe vyvoláva to najlepšie.", author: "Epictetus" },
  { text: "Dostali sme život — nie dobrý alebo zlý. Je na tebe, aby si z neho urobil dobrý alebo zlý.", author: "Epictetus" },
  { text: "Nikto ti nemôže ublížiť bez tvojho súhlasu.", author: "Epictetus" },
  { text: "Pokrok sa nedosahuje šťastím ani náhodou, ale každodennou prácou na sebe.", author: "Epictetus" },
  { text: "Čím väčšia ťažkosť, tým viac slávy pri jej prekonaní.", author: "Epictetus" },
  { text: "Vedz najprv, kto si; a potom sa podľa toho ozdob.", author: "Epictetus" },
  { text: "Ak sa chceš zlepšiť, buď spokojný s tým, že ťa budú považovať za hlúpeho.", author: "Epictetus" },
];

/**
 * Returns a deterministic quote for the given date.
 * Same date = same quote (all day); changes at midnight. No randomness — consistent across devices.
 * Uses locale for translation.
 */
export function getQuoteForDate(date: Date, locale: SupportedLocale = "en"): StoicQuote {
  const dateStr = date.toISOString().slice(0, 10);
  const quotes = locale === "sk" ? STOIC_QUOTES_SK : STOIC_QUOTES;
  const index =
    dateStr
      .split("")
      .reduce((a, c) => a + c.charCodeAt(0), 0) % quotes.length;
  return quotes[index];
}
